# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db4a1b536be1ae5a997620cd9c132b64836404005b87e0683475fd2d15440ea37bf3790f9956294fad5522a97703445e55beb144485acede4ebdcb69a88f467c

test:
  secret_key_base: b8c49636891480ef4bcd80e2664c2d17fb452ddce59b8a7d1fa1909eb3a5ca071c636ed0749c44550f739787bb4049921c3a79abb2932b19958dc36b144b4a40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
